### PR TITLE
Closes #367 Change rule from 1 to 2 to return always a value

### LINKED ISSUE #367: OneParExpNormalPrior - skel_fun_inv produce NA
The following code is also part of the JSS publication (Bove et al. 2019) which provides code for the one-parameter CRM (O’Quigley et al. 1990):

https://github.com/Roche/crmPack/blob/d7cb6def0d43ba7cffbb439b367feda027934991/R/Model-class.R#L2621-L2622

Two interpolation functions are introduced to be able to get any DLT prob over the dose range and any dose for a given DLT probability. 

In the function skel_fun_inv the parameter rule=1 is specified. That means that NAs are returned when the prob is outside the range of skel_probs. The Problem is that crmPack cannot deal with NAs in some context (e.g. next best dose) and therefore simulations runs into errors.

I think that rule=2 fix the problem (lowest or highest dose is returned when prob outside skel_probs), return what we want and is in line with the behavior of crmPack (to always return a dose).

I am not sure if there was a reason to choose rule=1 in the JSS paper, therefore I also ask @TJaki for input to this issue.

### PR DESCRIPTION
**Pull request by 0liver0815**
Closes #367

### CODE REVIEW

**Review by danielinteractive — APPROVED** [review]

**Comment by danielinteractive** [comment]
@0liver0815 thanks again, if possible it would be best to even have a small test that fails because there is NA in the current version, and then shows that it works now

**Comment by danielinteractive** [comment]
@0liver0815 I think here just a test is missing?

**Comment by 0liver0815** [comment]
@danielinteractive I am working on a test. I think I will commit today. Then the request can be merged.

**Comment by 0liver0815** [comment]
@danielinteractive Test case added.

**Pull request merged**
