### PR TITLE
650 ordinal crm part 1

### PR DESCRIPTION
**Pull request by Puzzled-Face**
Draft for review

### CODE REVIEW

**Comment by danielinteractive** [comment]
Thanks @Puzzled-Face , this contains too much material for me to easily review, can we please instead do this in small steps? Ideally each PR should contain one new class / function with its documentation and tests etc.
This will also help to keep the branches shortlived and avoid merge conflicts.

**Comment by Puzzled-Face** [comment]
> Thanks @Puzzled-Face , this contains too much material for me to easily review, can we please instead do this in small steps? Ideally each PR should contain one new class / function with its documentation and tests etc. This will also help to keep the branches shortlived and avoid merge conflicts.

Unfortunately, I believe this is just about the smallest _practically useful_ update that is possible.  If we break it down further, Changes introduced in early steps will not be fully explained or testable until later in the implementation process.  That said, if that is the route we wish to take, I suggest the following (based on the list at the start of Issue #650)...

1. The `DataOrdinal` class, including `update`, `dose_grid_range` and `plot` methods
2. The `LogisticLogNormalOrdinal` class
3. `mcmc-LogisticLogNormalOrdinal` method
4. `prob-LogisticLogNormalOrdinal`, `dose-LogisticLogNormalOrdinal` methods
5. `fit-LogisticLogNormalOrdinal`, `plot-Samples-DataOrdinal` methods
6. First draft of a "How to" vignette
7. `doseFunction-LogisticLogNormalOrdinal` and `probFunction-LogisticLogNormalOrdinal`
8. `CohortSizeOrdinal` class
9. `IncrementsOrdinal` class
10. `MaxDoseOrdinal` class
11. `NextBestOrdinal` class

Each step would include appropriate examples and tests for new and changed methods and classes.  Steps 7-11 would include updates to the vignette.

**Comment by danielinteractive** [comment]
Thanks @Puzzled-Face that would be exactly what I need!

**Comment by Puzzled-Face** [comment]
Closed as per discussion above, to be replaced with several smaller, incremental issues and PRs.

**Pull request closed without merging**
