### PR TITLE
Closes #178

### LINKED ISSUE #178: Clean up `ModelEff` class
Please edit appropriately below if needed.

To do:

- [x] Revise documentation
  - [x] RStudio outline section dividers (use `# function or class name ----`)
  - [x] Add lifecycle badge (as a default take "stable" for existing functions or classes)
  - [x] Replace `##'` by `#'`
  - [x] Add to `pkgdown.yml`
  - [x] Remove file history and the timestamp in comments on top of file
- [x] Add unit tests
  - [x] For classes:
    - [x] Test default constructor
    - [x] For reference classes: test methods
  - [x] For functions: as usual
- [x] Refactor as needed
  - [x] Code styling (indentation etc.) - install package `styler` and use corresponding add-in
  - [x] Keep externally used names so that we don't break downstream code
  - [x] Remove `keywords` tags
  - [x] For functions or methods:
    - [x] Add assertions for arguments using `checkmate` functions
    - [x] If it is too long, break up into pieces (rule of thumb: maximum 50 lines of code)
    - [x] Consider renaming internal variables etc. if needed
    - [x] Avoid explicit use of `return`
  - [x] For classes:
    - [x] move function definitions outside if possible (e.g. move validation function as `validity_subjects()` to `Data-validity.R` and have corresponding test file `test-Data-validity.R`)
    - [x] In `setClass` function, just use the `slots` instead of outdated `representation`
    - [x] Remove things like `validObject(.Data())`

### PR DESCRIPTION
**Pull request by wwojciech**
Closes #178

### CODE REVIEW

**Review by danielinteractive — APPROVED** [review]
thx Wojciech, nice!

**Comment by wwojciech** [comment]
@danielinteractive I need to also supply `efficacyFunction` and `doseFunction` for `ModelEff`. Maybe I can somehow combine it with `ModelTex`....

**Comment by dinakar29** [comment]
> Hi @dinakar29 Do you know why this fails at some strange stage? Tx!

I've reported this to Github. Not sure why it's failing with that error.

**Comment by wwojciech** [comment]
> > Hi @dinakar29 Do you know why this fails at some strange stage? Tx!
> 
> I've reported this to Github. Not sure why it's failing with that error.

Thanks a lot @dinakar29 , Do you think this is also responsible for `Spell Check` failure? The message does not say to much and I cannot see if there are any spelling error which I should correct... Tx again!

**Comment by dinakar29** [comment]
> Thanks a lot @dinakar29 , Do you think this is also responsible for `Spell Check` failure? The message does not say to much and I cannot see if there are any spelling error which I should correct... Tx again!

Yes, the spellcheck issue also looks like it is related to the ongoing incident: https://www.githubstatus.com/incidents/vxvyrmy9w1vp

**Pull request merged**
