### PR TITLE
 `broom`-like `tidy` and `glimpse` methods

### PR DESCRIPTION
**Pull request by PuzzledFace**
For discussion

### CODE REVIEW

**Comment by danielinteractive** [comment]
Thanks @PuzzledFace can you please merge main into this feature branch so I only see the design update? If that has conflicts please create new branch - thank you

**Comment by danielinteractive** [comment]
Actually I just saw that the pull request is in wrong direction- no need for PR if you update your own feature branch

**Comment by danielinteractive** [comment]
@wwojciech @PuzzledFace I think this PR needs to be closed and reopened in the other direction, can you please check?

**Comment by wwojciech** [comment]
Yes, I agree. Thanks @danielinteractive. So @PuzzledFace - I will close this one.

**Pull request closed without merging**
