### PR TITLE
Closes #418

### LINKED ISSUE #418: `StoppingGstarCIRatio` rules class cleanup
Please edit appropriately below if needed.

To do:

- [x] Revise documentation
  - [x] RStudio outline section dividers (use `# function or class name ----`)
  - [x] Add lifecycle badge (as a default take "stable" for existing functions or classes)
  - [x] Replace `##'` by `#'`
  - [x] Add to `pkgdown.yml`
  - [x] Remove file history and the timestamp in comments on top of file
- [x] Add unit tests
  - [x] For classes:
    - [x] Test default constructor
    - [x] For reference classes: test methods
  - [x] For functions: as usual
- [x] Refactor as needed
  - [x] Code styling (indentation etc.) - install package `styler` and use corresponding add-in
  - [x] Keep externally used names so that we don't break downstream code
  - [x] Remove `keywords` tags
  - [x] For functions or methods:
    - [x] Add assertions for arguments using `checkmate` functions
    - [x] If it is too long, break up into pieces (rule of thumb: maximum 50 lines of code)
    - [x] Consider renaming internal variables etc. if needed
    - [x] Avoid explicit use of `return`
  - [x] For classes:
    - [x] move function definitions outside if possible (e.g. move validation function as `validity_subjects()` to `Data-validity.R` and have corresponding test file `test-Data-validity.R`)
    - [x] In `setClass` function, just use the `slots` instead of outdated `representation`
    - [x] Remove things like `validObject(.Data())`

### PR DESCRIPTION
**Pull request by wwojciech**
Closes #418

### CODE REVIEW

**Review by danielinteractive — APPROVED** [review]

**Comment by wwojciech** [comment]
Hi @cicdguy - we have some `gitleaks` issue here, could you pl. have a look at this? Thanks!

**Comment by wwojciech** [comment]
> > Hi @cicdguy - we have some `gitleaks` issue here, could you pl. have a look at this? Thanks!
> 
> Thanks for the report. Looking into it now.

Thanks. Also, I do not know why the `nextBest.Rd` file is constantly (wrongly) overwritten by the automation. Specifally, the part about the `NextBestTDsamples` examples is removed. But it should not be. Tx!

**Comment by wwojciech** [comment]
Hi @cicdguy - it is unfortunately still hanging....

**Comment by wwojciech** [comment]
Hi Dinakar ( @cicdguy ) I am sorry for bothering but this problem with automation is a kind of blocking point and I cannot make a merge to continue my work. This happens since some days ago....

**Comment by wwojciech** [comment]
> @wwojciech Fixed here: [b614161](https://github.com/Roche/crmPack/commit/b61416162e43feebbd6aeff6f0e2a359188878f3)

Thanks @cicdguy - but it is still hanging!

**Comment by wwojciech** [comment]
@cicdguy - gitleaks and roxygen are failing.

**Pull request merged**
