### PR TITLE
Closes #146

### LINKED ISSUE #146: model class `DualEndpointBeta` clean up
Please edit appropriately below if needed.

To do:

- [x] Revise documentation
  - [x] RStudio outline section dividers (use `# function or class name ----`)
  - [x] Add lifecycle badge (as a default take "stable" for existing functions or classes)
  - [x] Replace `##'` by `#'`
  - [x] Add to `pkgdown.yml`
  - [x] Remove file history and the timestamp in comments on top of file
- [x] Add unit tests
  - [x] For classes:
    - [x] Test default constructor
    - [x] For reference classes: test methods
  - [x] For functions: as usual
- [x] Refactor as needed
  - [x] Code styling (indentation etc.) - install package `styler` and use corresponding add-in
  - [x] Keep externally used names so that we don't break downstream code
  - [x] Remove `keywords` tags
  - [x] For functions or methods:
    - [x] Add assertions for arguments using `checkmate` functions
    - [x] If it is too long, break up into pieces (rule of thumb: maximum 50 lines of code)
    - [x] Consider renaming internal variables etc. if needed
    - [x] Avoid explicit use of `return`
  - [x] For classes:
    - [x] move function definitions outside if possible (e.g. move validation function as `validity_subjects()` to `Data-validity.R` and have corresponding test file `test-Data-validity.R`)
    - [x] In `setClass` function, just use the `slots` instead of outdated `representation`
    - [x] Remove things like `validObject(.Data())`

### PR DESCRIPTION
**Pull request by wwojciech**
Closes #146 (missing helper unit tests, no help)

### CODE REVIEW

**Comment by wwojciech** [comment]
Hi @danielinteractive 

I am subbmiting this draft PR, because I wanted to check with you if the `DualEndpointBeta` class is acceptable now. I created some helper function `h_model_dual_endpoint_beta`, but decided to leave these 4 blocks of code:


```
  start <- h_model_dual_endpoint_beta(
    use_fixed["E0"],
    param = E0,
    param_name = "E0",
    prior = function() {
      E0 ~ dunif(E0_low, E0_high)
    },
    de = start
  )
  ```
If this does not look good, I can extract it into separate wrapper function, one wrapper for whole blocks, or four wrappers, each one wrapper for a separate block of code. What do you think?

Tx!

**Review by danielinteractive — COMMENTED** [review]
thx @wwojciech , I think that looks good. In this case I would just leave this slightly duplicated code as is. Wrappers etc. will make it more difficult to modify later here.

**Comment by wwojciech** [comment]
Hi @dinakar29 Do you know what the automated checks are not started here? Thanks a lot for checking!

**Comment by dinakar29** [comment]
Hi, there is an ongoing issue with Github Actions at the moment: https://www.githubstatus.com/incidents/y5hdmv0p49x3

**Comment by danielinteractive** [comment]
@wwojciech there are still some tests missing right?

**Comment by wwojciech** [comment]
> @wwojciech there are still some tests missing right?

Hi @danielinteractive , Nope, all tests should be in place now and the PR is ready for review.

**Review by danielinteractive — APPROVED** [review]
thx Wojciech, nice work!

**Pull request merged**
