### PR TITLE
Remove plot.gtable and print.gtable

### PR DESCRIPTION
**Pull request by Puzzled-Face**
Part of #683.

### CODE REVIEW

**Review by danielinteractive — APPROVED** [review]

**Comment by danielinteractive** [comment]
@Puzzled-Face I think we just need to revert this PR to fix #716 . I think we should not use any `grid.draw()` explicitly elsewhere

**Comment by Puzzled-Face** [comment]
We could retain this PR (thus removing `print.gtable` and `plot.gtable` - a small but reasonable simplification) and revise #716 to replace new and existing calls to `grid.draw()` with `gridExtra::grid.arrange()`.  That seems to give us the best of both worlds...

**Comment by Puzzled-Face** [comment]
"Sorry, this pull request couldn’t be reverted automatically. It may have already been reverted, or the content may have changed since it was merged."

**Comment by danielinteractive** [comment]
Yeah I guess you might need to make a "manual revert" of this PR, by adding the contents this PR deleted in a new PR

**Pull request merged**
