### PR TITLE
Closes #254

### LINKED ISSUE #254: Rules `NextBestInfTheory` class cleanup
Please edit appropriately below if needed.

To do:

- [ ] Revise documentation
  - [ ] RStudio outline section dividers (use `# function or class name ----`)
  - [ ] Add lifecycle badge (as a default take "stable" for existing functions or classes)
  - [ ] Replace `##'` by `#'`
  - [ ] Add to `pkgdown.yml`
  - [ ] Remove file history and the timestamp in comments on top of file
- [ ] Add unit tests
  - [ ] For classes:
    - [ ] Test default constructor
    - [ ] For reference classes: test methods
  - [ ] For functions: as usual
- [ ] Refactor as needed
  - [ ] Code styling (indentation etc.) - install package `styler` and use corresponding add-in
  - [ ] Keep externally used names so that we don't break downstream code
  - [ ] Remove `keywords` tags
  - [ ] For functions or methods:
    - [ ] Add assertions for arguments using `checkmate` functions
    - [ ] If it is too long, break up into pieces (rule of thumb: maximum 50 lines of code)
    - [ ] Consider renaming internal variables etc. if needed
    - [ ] Avoid explicit use of `return`
  - [ ] For classes:
    - [ ] move function definitions outside if possible (e.g. move validation function as `validity_subjects()` to `Data-validity.R` and have corresponding test file `test-Data-validity.R`)
    - [ ] In `setClass` function, just use the `slots` instead of outdated `representation`
    - [ ] Remove things like `validObject(.Data())`

### PR DESCRIPTION
**Pull request by wwojciech**
Closes #254

### CODE REVIEW

**Comment by wwojciech** [comment]
Hi @danielinteractive - I had to slightly modify/rearrange few existing unit tests for `Rules` classes. I remember it would be better to start a new PR for such a separate modifications, but I initially thought it would be very small - but ended up with a bit more than I expected :(. I do apologise for the inconveniences caused.

**Review by danielinteractive — APPROVED** [review]
thx Wojciech, looks good to me! maybe try pinging @pc494 in case he can have a quick look too? (re: default values e.g.)

**Comment by wwojciech** [comment]
Tx @danielinteractive 
I actually checked it a bit with this document - https://onlinelibrary.wiley.com/doi/10.1002/sim.8450, but sure I will let Phillip know about it.

**Comment by wwojciech** [comment]
Hi Phillip (@pc494) !
Within this issue and PR I refactored `NextBestInfTheory` Rules class you created. Daniel suggested it would be good if you have a time to look at it after my refactoring to ensure default values and validation function I created makes sense. Tx!

**Comment by wwojciech** [comment]
Thanks a lot Phillipe @pc494 !

**Pull request merged**
